import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const __dirname = dirname(fileURLToPath(import.meta.url));

function copyWasm() {
	const src = join(__dirname, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
	const dest = join(__dirname, 'sql-wasm.wasm');
	if (existsSync(src)) {
		copyFileSync(src, dest);
		console.log('Copied sql-wasm.wasm');
	}
}

copyWasm();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	// BRAT 只下发 main.js：把 sql.js wasm 打进包，避免侧边栏因缺 wasm 白屏
	loader: {
		'.wasm': 'binary',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
